version: "3"

volumes:
  node_modules:
services:
  nuxt:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/node_modules